packages:
  - playground

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  simple-git-hooks: true

ignoredBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
onlyBuiltDependencies:
  - simple-git-hooks
