packages:
  - playground

allowBuilds:
  '@parcel/watcher': false
  esbuild: false
  simple-git-hooks: true

ignoredBuiltDependencies:
  - "@parcel/watcher"
  - esbuild
minimumReleaseAgeExclude:
  - h3@2.0.1-rc.26
onlyBuiltDependencies:
  - simple-git-hooks
